# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
command_timeout = 1000
scan_timeout = 1000

[git_branch]
# symbol = "🌱 "

[git_commit]
# tag_symbol = "🔖 "

[directory]
truncation_length = 8
truncation_symbol = "…/"
truncate_to_repo = false

[aws]
disabled = true
style = "bold #ffb86c"

[gcloud]
disabled = true

[battery]
disabled = true

[bun]
disabled = true
